apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-deployment
  template:
    metadata:
      labels:
        app: app-deployment
    spec:
      containers:
        - name: app-deployment
          image: vishwasraiborde19/tasks:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
      restartPolicy: Always
