apiVersion: v1
kind: Service
metadata:
  name: discover-server-svc
spec:
  selector:
    app: disco
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: NodePort
  externalIPs:
    - 192.168.49.2
  