apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-ms
  template:
    metadata:
      labels:
        app: task-ms
    spec:
      containers:
        - name: task-ms
          image: vishwasraiborde19/task-ms:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
      restartPolicy: Always
