apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: platform
  name: user-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-ms
  template:
    metadata:
      labels:
        app: user-ms
    spec:
      containers:
        - name: task-ms
          image: vishwasraiborde19/user-ms:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9001
      restartPolicy: Always
