apiVersion: v1
kind: Service
metadata:
  namespace: platform
  name: user-ms-svc
spec:
  selector:
    app: user-ms
  ports:
    - protocol: "TCP"
      port: 9001
      targetPort: 9001
  type: NodePort
  