apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
  namespace: platform
  labels:
    app: admin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      name: admin-server
      labels:
        app: admin-server
    spec:
      containers:
        - name: admin
          image: vishwasraiborde19/admin-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      restartPolicy: Always
      