apiVersion: v1
kind: Service
metadata:
  name: admin-server-svc
  namespace: platform
spec:
  selector:
    app: admin-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

  