apiVersion: v1
kind: Service
metadata:
  name: admin-server-svc
spec:
  selector:
    app: admin-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
  externalIPs:
    - 192.168.49.2
  