apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-dp
  labels:
    app: config-server-dp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server-dp
  template:
    metadata:
      name: config-server-dp
      labels:
        app: config-server-dp
    spec:
      containers:
        - name: config-server-dp
          image: Image
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      